/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_delimiter = 1,
  anon_sym_COLON = 2,
  sym_header_name = 3,
  sym_header_value = 4,
  sym__whitespace = 5,
  anon_sym_LF = 6,
  anon_sym_CR = 7,
  anon_sym_CR_LF = 8,
  anon_sym_NULL = 9,
  sym__data = 10,
  sym_source_file = 11,
  sym_delimiter_line = 12,
  sym_header = 13,
  sym_body = 14,
  sym__newline = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_source_file_repeat2 = 17,
  aux_sym_body_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_delimiter] = "delimiter",
  [anon_sym_COLON] = ":",
  [sym_header_name] = "header_name",
  [sym_header_value] = "header_value",
  [sym__whitespace] = "_whitespace",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_NULL] = "\0",
  [sym__data] = "_data",
  [sym_source_file] = "source_file",
  [sym_delimiter_line] = "delimiter_line",
  [sym_header] = "header",
  [sym_body] = "body",
  [sym__newline] = "_newline",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_delimiter] = sym_delimiter,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name] = sym_header_name,
  [sym_header_value] = sym_header_value,
  [sym__whitespace] = sym__whitespace,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_NULL] = anon_sym_NULL,
  [sym__data] = sym__data,
  [sym_source_file] = sym_source_file,
  [sym_delimiter_line] = sym_delimiter_line,
  [sym_header] = sym_header,
  [sym_body] = sym_body,
  [sym__newline] = sym__newline,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_delimiter] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [sym__whitespace] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [sym__data] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_delimiter_line] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if ((!eof && lookahead == 00)) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(10);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 1:
      if ((!eof && lookahead == 00)) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if ((!eof && lookahead == 00)) ADVANCE(14);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(11);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_delimiter);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_header_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_header_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__whitespace);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(12);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_CR_LF);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_NULL);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__data);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__data);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__data);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name] = ACTIONS(1),
    [sym__whitespace] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_CR] = ACTIONS(1),
    [anon_sym_CR_LF] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(19),
    [sym_delimiter_line] = STATE(3),
    [aux_sym_source_file_repeat2] = STATE(16),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_delimiter] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    ACTIONS(9), 1,
      sym_header_name,
    ACTIONS(13), 1,
      anon_sym_CR,
    STATE(4), 1,
      sym__newline,
    STATE(5), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [22] = 5,
    ACTIONS(9), 1,
      sym_header_name,
    ACTIONS(13), 1,
      anon_sym_CR,
    STATE(4), 1,
      sym__newline,
    STATE(5), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(11), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [41] = 4,
    STATE(20), 1,
      sym_body,
    ACTIONS(15), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(8), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(17), 3,
      anon_sym_CR,
      anon_sym_NULL,
      sym__data,
  [58] = 5,
    ACTIONS(9), 1,
      sym_header_name,
    ACTIONS(21), 1,
      anon_sym_CR,
    STATE(6), 1,
      sym__newline,
    STATE(9), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(19), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [77] = 4,
    STATE(22), 1,
      sym_body,
    ACTIONS(15), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(8), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(17), 3,
      anon_sym_CR,
      anon_sym_NULL,
      sym__data,
  [94] = 4,
    ACTIONS(23), 1,
      sym_delimiter,
    ACTIONS(25), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(7), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(28), 3,
      anon_sym_CR,
      anon_sym_NULL,
      sym__data,
  [111] = 4,
    ACTIONS(31), 1,
      sym_delimiter,
    ACTIONS(33), 2,
      anon_sym_LF,
      anon_sym_CR_LF,
    STATE(7), 2,
      sym__newline,
      aux_sym_body_repeat1,
    ACTIONS(35), 3,
      anon_sym_CR,
      anon_sym_NULL,
      sym__data,
  [128] = 4,
    ACTIONS(37), 1,
      sym_header_name,
    ACTIONS(42), 1,
      anon_sym_CR,
    STATE(9), 2,
      sym_header,
      aux_sym_source_file_repeat1,
    ACTIONS(40), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [144] = 2,
    ACTIONS(46), 1,
      anon_sym_CR,
    ACTIONS(44), 5,
      ts_builtin_sym_end,
      sym_header_name,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [155] = 3,
    ACTIONS(50), 1,
      anon_sym_CR,
    STATE(12), 1,
      sym__newline,
    ACTIONS(48), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [167] = 2,
    ACTIONS(46), 1,
      anon_sym_CR,
    ACTIONS(44), 4,
      sym_header_name,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [177] = 3,
    ACTIONS(54), 1,
      anon_sym_CR,
    STATE(14), 1,
      sym__newline,
    ACTIONS(52), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [189] = 2,
    ACTIONS(58), 1,
      anon_sym_CR,
    ACTIONS(56), 4,
      sym_header_name,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [199] = 3,
    ACTIONS(62), 1,
      anon_sym_CR,
    STATE(10), 1,
      sym__newline,
    ACTIONS(60), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_NULL,
  [211] = 3,
    ACTIONS(64), 1,
      sym_delimiter,
    STATE(2), 1,
      sym_delimiter_line,
    STATE(17), 1,
      aux_sym_source_file_repeat2,
  [221] = 3,
    ACTIONS(66), 1,
      sym_delimiter,
    STATE(3), 1,
      sym_delimiter_line,
    STATE(17), 1,
      aux_sym_source_file_repeat2,
  [231] = 1,
    ACTIONS(69), 1,
      anon_sym_COLON,
  [235] = 1,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
  [239] = 1,
    ACTIONS(73), 1,
      sym_delimiter,
  [243] = 1,
    ACTIONS(75), 1,
      sym_header_value,
  [247] = 1,
    ACTIONS(77), 1,
      sym_delimiter,
  [251] = 1,
    ACTIONS(79), 1,
      sym__whitespace,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 41,
  [SMALL_STATE(5)] = 58,
  [SMALL_STATE(6)] = 77,
  [SMALL_STATE(7)] = 94,
  [SMALL_STATE(8)] = 111,
  [SMALL_STATE(9)] = 128,
  [SMALL_STATE(10)] = 144,
  [SMALL_STATE(11)] = 155,
  [SMALL_STATE(12)] = 167,
  [SMALL_STATE(13)] = 177,
  [SMALL_STATE(14)] = 189,
  [SMALL_STATE(15)] = 199,
  [SMALL_STATE(16)] = 211,
  [SMALL_STATE(17)] = 221,
  [SMALL_STATE(18)] = 231,
  [SMALL_STATE(19)] = 235,
  [SMALL_STATE(20)] = 239,
  [SMALL_STATE(21)] = 243,
  [SMALL_STATE(22)] = 247,
  [SMALL_STATE(23)] = 251,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_delimiter_line, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_delimiter_line, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 5, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header, 5, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(11),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [71] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_multipart(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "multipart",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
